#!/usr/bin/env bash
# =============================================================================
# 1_setup_download.sh — Install TensorFold and download Qwen3.8-27B
#
# TensorFold (https://github.com/ashhart/TensorFold) serves this family from
# the tested MLX 4-bit checkpoint. Lane kernels want 4-bit weights in groups
# of 64. The mtplx sibling's mlx-community / Youssofal ids are a different
# conversion and are not the default here.
#
#   HF model   Vontra/Qwen3.8-27B-MLX-4bit     (~16.1 GB)
#   Drafter    z-lab/Qwen3.8-27B-DFlash2       (~3.8 GB, optional)
#
# Usage:
#   ./1_setup_download.sh                 # venv + CLI + model + drafter
#   ./1_setup_download.sh --deps-only     # venv + CLI only
#   ./1_setup_download.sh --no-drafter    # model only (serial / no DFlash2)
#   ./1_setup_download.sh org/repo        # different main checkpoint
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VENV_DIR="${SCRIPT_DIR}/venv"
CONFIG_FILE="${SCRIPT_DIR}/.tensorfold_config"

DEFAULT_MODEL="Vontra/Qwen3.8-27B-MLX-4bit"
DEFAULT_DRAFTER="z-lab/Qwen3.8-27B-DFlash2"
MODEL_ALIAS="${QWEN38_ALIAS:-qwen3.8-27b-tensorfold}"
CONTEXT="${QWEN38_CONTEXT:-262144}"

DEPS_ONLY=false
WITH_DRAFTER=true
MODEL="${QWEN38_HF_MODEL:-${DEFAULT_MODEL}}"

for arg in "$@"; do
    case "${arg}" in
        --deps-only|deps-only) DEPS_ONLY=true ;;
        --no-drafter) WITH_DRAFTER=false ;;
        --help|-h)
            sed -n '3,18p' "$0" | sed 's/^# \?//'
            exit 0
            ;;
        *)
            MODEL="${arg}"
            ;;
    esac
done

if [[ "$(uname -m)" != "arm64" ]]; then
    echo "ERROR: TensorFold on macOS needs Apple Silicon (arm64). Got $(uname -m)."
    exit 1
fi

pick_python() {
    local candidate ver major minor
    for candidate in /opt/homebrew/bin/python3.12 python3.12 python3; do
        if ! command -v "${candidate}" >/dev/null 2>&1; then
            continue
        fi
        ver="$("${candidate}" -c 'import sys; print(f"{sys.version_info[0]}.{sys.version_info[1]}")')"
        major="${ver%%.*}"
        minor="${ver#*.}"
        if [[ "${major}" -ge 3 && "${minor}" -ge 11 ]]; then
            command -v "${candidate}"
            return 0
        fi
    done
    return 1
}

PY="$(pick_python)" || {
    echo "ERROR: TensorFold needs Python 3.11+. Install it with: brew install python@3.12"
    exit 1
}

echo "→ Python: ${PY} ($("${PY}" --version))"
echo "→ Model:  ${MODEL}"
if [[ "${WITH_DRAFTER}" == true ]]; then
    echo "→ Draft:  ${DEFAULT_DRAFTER}"
else
    echo "→ Draft:  off"
fi

if [[ ! -d "${VENV_DIR}" ]]; then
    echo "→ Creating venv at ${VENV_DIR}"
    "${PY}" -m venv "${VENV_DIR}"
fi

# shellcheck source=/dev/null
source "${VENV_DIR}/bin/activate"
python -m pip install --upgrade pip
python -m pip install "git+https://github.com/ashhart/TensorFold.git"

echo "→ $(tensorfold --version)"
echo ""
tensorfold models
echo ""
echo "→ Checking ${MODEL} (config.json only, no weights) ..."
if ! tensorfold info "${MODEL}"; then
    echo "ERROR: tensorfold info failed for ${MODEL}."
    echo "       This CLI only serves families it has kernels for."
    exit 1
fi

DRAFTER=""
if [[ "${WITH_DRAFTER}" == true ]]; then
    DRAFTER="${DEFAULT_DRAFTER}"
fi

cat > "${CONFIG_FILE}" <<EOF
# Generated by 1_setup_download.sh. Re-run that script to change it.
HF_MODEL=${MODEL}
DRAFTER=${DRAFTER}
MODEL_ALIAS=${MODEL_ALIAS}
CONTEXT=${CONTEXT}
EOF
echo "→ Wrote ${CONFIG_FILE}"

if [[ "${DEPS_ONLY}" == true ]]; then
    echo "→ --deps-only: skipping weight download."
    echo "  Pull later with: ./2_start_tensorfold.sh   (it resumes the download)"
    exit 0
fi

echo ""
echo "→ Downloading weights into the Hugging Face cache ..."
if [[ -n "${DRAFTER}" ]]; then
    tensorfold pull "${MODEL}" "${DRAFTER}"
else
    tensorfold pull "${MODEL}"
fi

echo ""
echo "============================================================"
echo "  SETUP DONE"
echo "============================================================"
echo "  Model:   ${MODEL}"
echo "  Drafter: ${DRAFTER:-none}"
echo "  Alias:   ${MODEL_ALIAS}"
echo "  Next:    ./2_start_tensorfold.sh"
echo "============================================================"
